#define SERV_PORT 5000

#define GET_FASTONOSQL_VERSION "FASTONOSQL_VERSION"
#define GET_FASTOREDIS_VERSION "FASTOREDIS_VERSION"

#define FASTONOSQL_URL "www.fastoredis.com"
#define FASTOREDIS_URL "www.fastoredis.com"
